### PR TITLE
Export

### LINKED ISSUE #2: ENH: support exporting
If we want to use portable filestore as a bridge between the NSLS and home institution databrokers (using mongo backends) we need a way for portable filestore to export data.

Example workflow
NSLS_DB -> Portable_MDS/Portable_FS (on external disk) -> Home_DB (using Mongo)

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #2

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@tacaswell @arkilic @danielballan Ready for review!

**Comment by danielballan** [comment]
When a function is referenced as self._api.some_func, that function is expected to be implemented in core. Some are still missing.

**Comment by CJ-Wright** [comment]
@danielballan I think this is ready for another round of review

**Comment by CJ-Wright** [comment]
I think this has been taken care of by #4

**Pull request closed without merging**
